name: Test, Build and Push

on:
  push:
    branches: 
      - main

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker images
      run: docker-compose build
      
    - name: Run tests
      run: make ci
      
    - name: Cleanup
      run: docker-compose down